version: '3'

services:

  api:
    image: thecodingmachine/php:8.2-v4-apache
    ports:
      - "8085:80"
    volumes:
      - .:/var/www/html
    environment:
      APACHE_DOCUMENT_ROOT: public/

  database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "$MYSQL_ROOT_PASSWORD"
      MYSQL_DATABASE: "$MYSQL_DATABASE"
      MYSQL_USER: "$MYSQL_USER"
      MYSQL_PASSWORD: "$MYSQL_PASSWORD"
    ports:
      - "4306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:639"
      - "8001:8001"
    volumes:
      - redis_data:/data

volumes:
###> doctrine/doctrine-bundle ###
  mysql_data:
  redis_data:
###< doctrine/doctrine-bundle ###

